### ISSUE TITLE
Nemožnosť overiť výkaz

### ISSUE THREAD

**Issue by IvanSipka** [alexanderzatko/rovas#156]
Dobrý deň,
  bol som vyzvaný overiť výkaz https://rovas.app/node/142604 ale tlačidlo "Overiť" je neaktívne. Predpokladám že je to chyba.
Prosím pozrite sa na to, nerád by som dostal pokutu za nesplnenie povinnosti.
Ďakujem.

**Comment by alexanderzatko** [comment]
To bude asi programova chyba. Vasu vyzvu na overenie som vymazal, ale tento zaznam tu ponechame, pre pripad ze sa problem zopakuje.

Dakujem za report

**Comment by alexanderzatko** [comment]
Closing this issue as there is another one written in English. That might allow future reporters who do not speak Slovak to find it.
