### ISSUE TITLE
Called to verify an already verified task

### ISSUE THREAD

**Issue by lucumon** [alexanderzatko/rovas#158]
Hi! Today in entered to rovas in order to verify some tasks that I was called to verify but, one of them is already verified and it won't let me verify it. Screenshot:
![image](https://user-images.githubusercontent.com/24960275/169699258-62194961-24d8-468c-8b93-c9bd93a07bb7.png)

Thanks for your awesome work!

**Comment by alexanderzatko** [comment]
yeah, this seems to happen from time to time as another user reported the [same problem recently](https://github.com/alexanderzatko/rovas/issues/156). 

I deleted your obligation. Thanks for the report and compliment :-)

... I will leave this issue open and close the related one.

**Comment by alexanderzatko** [comment]
this bug should be fixed now
