### ISSUE TITLE
Incorrect filter - extra br tag

### ISSUE THREAD

**Issue by miro-janosik** [alexanderzatko/rovas#159]
https://rovas.app/node/151746

Web Address: 
[https://osmcha.org/changesets/121317279?filters={"ids":[{"label":"121317279","value":"121317279"}],"date__gte":[{"label":"2022-05-21","value":"2022-05-21"}]}<br>](https://osmcha.org/changesets/121317279?filters={%22ids%22:[{%22label%22:%22121317279%22,%22value%22:%22121317279%22}],%22date__gte%22:[{%22label%22:%222022-05-21%22,%22value%22:%222022-05-21%22}]}%3Cbr%3E)

contains extra <br> at the end, and then osmcha does not display anything.

**Comment by alexanderzatko** [comment]
thanks for the report.

**Comment by alexanderzatko** [comment]
fixed
