### ISSUE TITLE
Incorrect deadline time in e-mail

### ISSUE THREAD

**Issue by miro-janosik** [alexanderzatko/rovas#161]
E-mail saying: 

This is a friendly reminder ...
Creating map data with JOSM
deadline: 09 Aug 2022 48:08:11

I can't verify the node https://rovas.app/node/164325
It also says different deadline time:
Called on verifiers: 
[MiroJ](https://rovas.app/user/2743) deadline: 9 Aug 2022 - 00:48

**Comment by alexanderzatko** [comment]
The incorrect time of the reminder was a bug - it is fixed now. The fact you can't verify the report is due to the fact that the deadline has passed already.

Thank you for the report
