### ISSUE TITLE
Cannot verify some reports

### ISSUE THREAD

**Issue by lucumon** [alexanderzatko/rovas#165]
Hi! I'm called to verify two reports, buy the verify button isn't working, so I can't fulfill my obligation. Here are two screenshots of the metioned reports.
![Captura de pantalla (7)](https://user-images.githubusercontent.com/24960275/189502329-daff9cef-c0ad-4645-87c0-fa3a14693bbf.png)
![Captura de pantalla (8)](https://user-images.githubusercontent.com/24960275/189502330-6a17b239-1e1e-4575-8bac-563b578c2944.png)

**Comment by lucumon** [comment]
Hi! Now I recieved a mail for both reports, warning me about my failure to verify, lowering my compliance score. Can someone fix this?
![8fe368d20145d889064cc9657ce50d1d](https://user-images.githubusercontent.com/24960275/189537119-2e09718b-63dc-403a-a358-0e8588acfa49.png)

**Comment by alexanderzatko** [comment]
Thanks for reporting the problem. We will restore your credit and look into the bug.

**Comment by lucumon** [comment]
Hi, this happened to me again. Here are screenshots of the reports with the issue.

![image](https://user-images.githubusercontent.com/24960275/191925257-f3f2c17a-8c94-4268-bd9d-b758a76ee9f9.png)
![image](https://user-images.githubusercontent.com/24960275/191925468-f93bfd5e-5534-4510-8744-804a71f03bd8.png)

**Comment by alexanderzatko** [comment]
Please try now. Rovas incorrectly set the cutoff date to the past midnight, whereas the verifier should have time until sometimes in the afternoon of the deadline day, to verify the report. The exact deadline time should be mentioned in the Verification request email.

Thanks for reporting and sorry for the inconvenience. If you confirm the issue fixed, I will close it.
