### ISSUE TITLE
Some reports don't have assigned verifiers 

### ISSUE THREAD

**Issue by BelKed** [alexanderzatko/rovas#166]
When I create a report, I usually have verifiers assigned to it immediately, or the next day. However, there are two reports of mine that don't have any verifiers assigned yet:

- https://rovas.app/node/171286 (created 12 days ago)
- https://rovas.app/node/172442 (created 5 days ago)

Is there anything wrong with these reports?

**Comment by alexanderzatko** [comment]
Thanks for the report. The NACE category was not chosen correctly in the listed reports for the job performed (see the picture below where the correct one is checked and the incorrect highlighted).

Regardless, Rovas should be able to find verifiers for such reports redardless. This requirement is covered in issue #167


<img width="634" alt="Screen Shot 2022-09-12 at 20 25 50" src="https://user-images.githubusercontent.com/3430677/189730526-bb61d0a3-1030-49b7-b2a6-0b61c4ee6e91.png">

**Comment by alexanderzatko** [comment]
oh yeah, I changed the NACE category and now the jobs are scheduled for verification

**Comment by BelKed** [comment]
Thanks for the response :)
I have chosen this category purposely – I wasn't drawing maps, but I was doing a survey (I was gathering the needed data outside) instead. So this one category seemed as correct to me.
